### ISSUE TITLE
java.lang.IllegalArgumentException: account must not be null

### ISSUE THREAD

**Issue by djangoa** [spacecowboy/NotePad#449]
### Description
Many thanks to everyone maintaining this app, I've used it for a very long time and glad to see it's still going :)

Unfortunately, an OTA update was pushed to my phone for Android 13 and the app no longer opens. I've updated to version 7.0.0 via fdroid but this didn't solve my issue.

Any help would be greatly appreciated.

### How To Reproduce

1. Open the APP 
2. Exits immediately with runtime exception

### Technical information

- Device: Xiaomi 12
- OS: MIUI 13.2.4.0 (TLCEUXM) / Android 13 (TKQ1.220807.001)
- App version: 7.0.0

### Log

```text
java.lang.RuntimeException: Unable to resume activity {com.nononsenseapps.notepad/com.nononsenseapps.notepad.ActivityMain_}: java.lang.IllegalArgumentException: account must not be null
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4917)
	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4950)
	at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:54)
	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2363)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8109)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
Caused by: java.lang.IllegalArgumentException: account must not be null
	at android.content.ContentResolver.isSyncActive(ContentResolver.java:3563)
	at com.nononsenseapps.helpers.SyncGtaskHelper.forceGTaskSyncNow(SyncGtaskHelper.java:34)
	at com.nononsenseapps.helpers.SyncGtaskHelper.requestSyncIf(SyncGtaskHelper.java:26)
	at com.nononsenseapps.notepad.ActivityMain.onResume(ActivityMain.java:25)
	at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1532)
	at android.app.Activity.performResume(Activity.java:8615)
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4907)
	... 13 more
```

**Comment by djangoa** [comment]
> Thank you for reaching out. Did you connect a google account to the app ? If so, did you use the google task sync functionality ?
> 
> The bug is very simple, I will fix it immediately, but you may have to wait a few days for the next release to appear on fdroid

Yes the app was previously connected to my google account and I had the task sync functionality enabled but not sure if I had disabled this at some point as this functionality stopped working for me a few years ago.

> Looking at it, the mistake was me assuming you have at least 1 google account on the device. Adding one should fix the bug right now. Or you can just wait for us to publish the next app update.

Can I add an account without being able to open the app? If not, I'll provide an update once the app is published on fdroid as I don't want to "clear all data" if I can avoid, it's been a while since I exported my notes.

Thanks for looking into this and providing a fix, much appreciated.

**Comment by djangoa** [comment]
@CampelloManuel I can confirm the issue is resolved. Many thanks!
